# Generated by Django 4.2.4 on 2024-03-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
