# Generated by Django 4.2.4 on 2024-04-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='role',
        ),
    ]
