# Generated by Django 4.2.4 on 2024-04-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0003_remove_membre_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='type_paiement',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
