# Generated by Django 4.2.4 on 2024-04-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0006_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
