# Generated by Django 4.2.4 on 2024-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0007_delete_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupetontine',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
