# Generated by Django 4.2.4 on 2024-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0009_remove_groupetontine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupetontine',
            name='montant_cotisation',
            field=models.CharField(max_length=100),
        ),
    ]
